require "sdl-crystal-bindings"

require "./util"
require "./renderable"
require "./line"
require "./window"

require "./ray_tracer/tuple"
require "./ray_tracer/color"
require "./ray_tracer/canvas"
require "./ray_tracer/matrix"
require "./ray_tracer/ray"
require "./ray_tracer/sphere"
require "./ray_tracer/intersection"
require "./ray_tracer/point_light"
require "./ray_tracer/material"
