require "sdl-crystal-bindings"

require "./util"
require "./renderable"
require "./line"
require "./window"

require "./ray_tracer/tuple"
require "./ray_tracer/color"
require "./ray_tracer/canvas"
require "./ray_tracer/matrix"
require "./ray_tracer/ray"
require "./ray_tracer/shape"
require "./ray_tracer/sphere"
require "./ray_tracer/plane"
require "./ray_tracer/intersection"
require "./ray_tracer/point_light"
require "./ray_tracer/material"
require "./ray_tracer/world"
require "./ray_tracer/computation"
require "./ray_tracer/camera"
require "./ray_tracer/pattern"
require "./ray_tracer/solid_pattern"
require "./ray_tracer/stripe_pattern"
require "./ray_tracer/gradient_pattern"
require "./ray_tracer/ring_pattern"
require "./ray_tracer/checkers_pattern"
require "./ray_tracer/blended_pattern"
